/home/robotlabx/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "enet_sanity.py", line 388, in <module>
    depth_loss = depth_criterion(pred, pcl.to(device))
  File "/home/robotlabx/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/robotlabx/Desktop/DTAI/decnet2022/src/models/criteria.py", line 17, in forward
    diff = target - pred
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!